const sampleProducts = [
  // Conduit Products
  {
    id: "SR6CT",
    name: "Rigid Conduit",
    pageUrl: "/index.php/home/products/rigid-conduit/",
    category: "Conduit",
    image: "/wp-content/uploads/2024/12/SS-Rigid-Conduit_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Conduit Type": "Rigid",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 6A", "CSA C22.1:21"],
    },
  },

  // Conduit Bodies
  {
    id: "SR6LB",
    name: "LB Conduit Body",
    pageUrl: "/index.php/home/products/lb-conduit-body/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/LB-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "LB",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6LL",
    name: "LL Conduit Body",
    pageUrl: "/index.php/home/products/ll-conduit-body/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/LL-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "LL",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6LR",
    name: "LR Conduit Body",
    pageUrl: "/index.php/home/products/lr-conduit-body/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/LR-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "LR",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6C",
    name: "C Conduit Body",
    pageUrl: "/index.php/home/products/c-conduit-body/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/C-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "C",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6T",
    name: "T Conduit Body",
    pageUrl: "/index.php/home/products/t-conduit-body//",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/T-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "T",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6TB",
    name: "TB Conduit Body",
    pageUrl: "/index.php/home/products/tb-conduit-body/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/TB-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "TB",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6XB",
    name: "XB Conduit Body",
    pageUrl: "/index.php/home/products/xb-conduit-body/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/XB-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "X",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },

  // Device Box
  {
    id: "SR6FD",
    name: "Device Box",
    pageUrl: "/index.php/home/products/device-box/",
    category: "Conduit Boxes",
    image: "/wp-content/uploads/2024/12/SS-Device-Box_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"'],
      "Material Grade": "316",
      "Box Style": "FDC",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },

  // Hubs
  {
    id: "SSTH",
    name: "Terminator Hub",
    pageUrl: "/index.php/home/products/terminator-hub/",
    category: "Conduit Boxes",
    image: "/wp-content/uploads/2024/12/SS-Terminator-Hub-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"'],
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: [""],
    },
  },

  // Liquid Tight
  {
    id: "LT-STR",
    name: "Liquid Tight Straight Connector",
    pageUrl: "/index.php/home/products/liquid-tight-straight-connector/",
    category: "Liquid Tight",
    image: "/wp-content/uploads/2024/12/SS-LT-Straight-Connector-min.png",
    specifications: {
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },

  {
    id: "LT-90",
    name: "Liquid Tight 90° Connector",
    pageUrl: "/index.php/home/products/liquid-tight-90-connector/",
    category: "Liquid Tight",
    image: "/wp-content/uploads/2024/12/SS-LT-90-Connector-min.png",
    specifications: {
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },

  {
    id: "LT-45",
    name: "Liquid Tight 45° Connector",
    pageUrl: "/index.php/home/products/liquid-tight-45-connector/",
    category: "Liquid Tight",
    image: "/wp-content/uploads/2024/12/SS-LT-45-Connector-min.png",
    specifications: {
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },

  // Elbows
  {
    id: "SR6EL45",
    name: "45° Elbow",
    pageUrl: "/index.php/home/products/45-elbow/",
    category: "Elbows",
    image: "/wp-content/uploads/2024/12/SS-45°-Elbow-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Elbow Angle": "45°",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },
  {
    id: "SR6EL90",
    name: "90° Elbow",
    pageUrl: "/index.php/home/products/90-elbow/",
    category: "Elbows",
    image: "/wp-content/uploads/2024/12/SS-90°-Elbow-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Elbow Angle": "90°",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },

  // Couplings
  {
    id: "SR6CPL",
    name: "Rigid Coupling",
    pageUrl: "/index.php/home/products/rigid-coupling/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/SS-Rigid-Coupling_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Coupling Style": "Standard",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },
  {
    id: "SR6CPL3P",
    name: "3-Piece Coupling",
    pageUrl: "/index.php/home/products/3-piece-coupling/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/3-Piece-Coupling-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Coupling Style": "3-Piece",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },
  // Nipples
  {
    id: "SSN",
    name: "Stainless Steel Nipple",
    pageUrl: "/index.php/home/products/nipples/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/SS-Nipple-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "304",
      "Coupling Style": "Standard",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },

  // Plugs & Bushings
  {
    id: "SSRP",
    name: "Recessed Plug",
    pageUrl: "/index.php/home/products/recessed-plug/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/SS-Recessed-Plug_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "304",
      "Coupling Style": "Standard",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },

  {
    id: "SSFB",
    name: "Face Bushing",
    pageUrl: "/index.php/home/products/face-bushing/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/SS_Face-Bushing-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "304",
      "Coupling Style": "Standard",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },

  // Strut
  {
    id: "STR-DEEP",
    name: "Deep Channel Slotted Strut",
    pageUrl: "/index.php/home/products/deep-strut-elongated-holes/",
    category: "Strut",
    image: "/wp-content/uploads/2024/12/SS-Deep-Strut-Slotted-min.png",
    specifications: {
      "Strut Properties": ["12 Gauge", '1⅝" x 1⅝"'],
      "Strut Pattern": "Slotted",
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },
  {
    id: "STR-SHALLOW",
    name: "Shallow Channel Slotted Strut",
    pageUrl: "/index.php/home/products/shallow-strut-elongated-holes/",
    category: "Strut",
    image: "/wp-content/uploads/2024/12/SS-Shallow-Strut-Slotted-min.png",
    specifications: {
      "Strut Properties": ["14 Gauge", '13/16" x 1⅝"'],
      "Strut Pattern": "Slotted",
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },
];

export default sampleProducts;
