const sampleProducts = [
  // Conduit Products
  {
    id: "SR6CT",
    name: "SS316 Rigid Conduit",
    pageUrl: "/products/rigid-conduit/",
    category: "Conduit",
    image: "/wp-content/uploads/2024/12/SS-Rigid-Conduit_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Conduit Type": "Rigid",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 6A", "CSA C22.1:21"],
    },
  },

  // Conduit Bodies
  {
    id: "SR6LB",
    name: "LB Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/LB-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "LB",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6LL",
    name: "LL Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/LL-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "LL",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6LR",
    name: "LR Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/LR-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "LR",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6C",
    name: "C Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/C-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "C",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6T",
    name: "T Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/T-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "T",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6TB",
    name: "TB Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/TB-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "TB",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },
  {
    id: "SR6XB",
    name: "XB Conduit Body",
    pageUrl: "/products/conduit-bodies/",
    category: "Conduit Bodies",
    image: "/wp-content/uploads/2024/12/XB-Conduit-Body_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Body Style": "X",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },

  // Device Box
  {
    id: "SR6FD",
    name: "FD Device Box",
    pageUrl: "/products/device-boxes/",
    category: "Conduit Boxes",
    image: "/wp-content/uploads/2024/12/SS-Device-Box_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"'],
      "Material Grade": "316",
      "Box Style": "FDC",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514A", "CSA C22.2 NO 18.1"],
    },
  },

  // Strut
  {
    id: "STR-DEEP",
    name: "Deep Strut Channel Slotted",
    pageUrl: "/products/strut/",
    category: "Strut",
    image: "/wp-content/uploads/2024/12/SS-Deep-Strut-Slotted-min.png",
    specifications: {
      "Strut Properties": ["12 Gauge", '1⅝" x 1⅝"'],
      "Strut Pattern": "Slotted",
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },
  {
    id: "STR-SHALLOW",
    name: "Shallow Strut Channel Slotted",
    pageUrl: "/products/strut/",
    category: "Strut",
    image: "/wp-content/uploads/2024/12/SS-Shallow-Strut-Slotted-min.png",
    specifications: {
      "Strut Properties": ["14 Gauge", '13/16" x 1⅝"'],
      "Strut Pattern": "Slotted",
      "Material Grade": "316",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
    },
  },

  // Couplings
  {
    id: "SR6CPL",
    name: "Standard Coupling",
    pageUrl: "/products/couplings/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/SS-Rigid-Coupling_v2-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Coupling Style": "Standard",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },
  {
    id: "SR6CPL3P",
    name: "3-Piece Coupling",
    pageUrl: "/products/couplings/",
    category: "Couplings",
    image: "/wp-content/uploads/2024/12/3-Piece-Coupling-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Coupling Style": "3-Piece",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },

  // Elbows
  {
    id: "SR6EL45",
    name: "45° Elbow",
    pageUrl: "/products/elbows/",
    category: "Elbows",
    image: "/wp-content/uploads/2024/12/SS-45°-Elbow-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Elbow Angle": "45°",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },
  {
    id: "SR6EL90",
    name: "90° Elbow",
    pageUrl: "/products/elbows/",
    category: "Elbows",
    image: "/wp-content/uploads/2024/12/SS-90°-Elbow-min.png",
    specifications: {
      "Trade Size": ['½"', '¾"', '1"', '1¼"', '1½"', '2"'],
      "Material Grade": "316",
      "Elbow Angle": "90°",
      Environment: [
        "Indoor",
        "Outdoor",
        "Corrosive",
        "Marine",
        "Chemical",
        "Food Processing",
        "Wet Location",
      ],
      Certification: ["UL 514B"],
    },
  },
];

export default sampleProducts;
